function t121_setHeight(recid){var rec=$('#rec'+recid);var div=$("#youtubeiframe"+recid);var height=div.width()*0.5625;div.height(height);div.parent().height(height);var videoLazy=rec.find('.t-video-lazyload');if(videoLazy!=undefined){var iframeLazy=videoLazy.find('iframe');var heightLazy=videoLazy.width()*0.5625;videoLazy.height(heightLazy);iframeLazy.height(heightLazy);setTimeout(function(){div=$("#youtubeiframe"+recid);div.height(div.width()*0.5625)},200)}}
function t132_unifyHeights(){$('.t132__box').children('.t132__wrappper').each(function(){$(this).children('a').children('div').css('width',$(this).outerWidth()-1);$(this).children('a').children('div').css('height',$(this).outerHeight()-40)})}
function t190_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t270_scroll(hash,offset,speed){if(hash.indexOf('#!/tproduct/')!==-1||hash.indexOf('#!/tab/')!==-1){return!0}
var root=$('html, body');var target="";if(speed===undefined){speed=500}
try{target=$(hash)}catch(event){console.log("Exception t270: "+event.message);return!0}
if(target.length===0){target=$('a[name="'+hash.substr(1)+'"]');if(target.length===0){return!0}}
var isHistoryChangeAllowed=!(window.location.hash===hash);root.animate({scrollTop:target.offset().top-offset},speed,function(){if(!isHistoryChangeAllowed){return}
if(history.pushState){history.pushState(null,null,hash)}else{window.location.hash=hash}
isHistoryChangeAllowed=!1});return!0}
function t397_init(recid){var el=$('#rec'+recid);var curMode=$('.t-records').attr('data-tilda-mode');var tabs=el.find('.t397__tab');if(curMode!='edit'&&curMode!='preview'){t397_scrollToTabs(recid)}
if(tabs.length>0){tabs.click(function(){el.find('.t397__tab').removeClass('t397__tab_active');$(this).addClass('t397__tab_active');t397_removeUrl();var tabNumber=el.find(".t397__tab_active").index()+1;if(curMode!='edit'&&curMode!='preview'&&tabNumber!==0){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',window.location.href+'#!/tab/'+recid+'-'+tabNumber)}}
t397_alltabs_updateContent(recid);t397_updateSelect(recid);var recids=$(this).attr('data-tab-rec-ids').split(',');recids.forEach(function(recid){var el=$('#rec'+recid);el.find('.t-feed, .t-store, .t117, .t121, .t132, .t223, .t226, .t228, .t229, .t230, .t268, .t279, .t341, .t346, .t347, .t349, .t351, .t353, .t384, .t385, .t386, .t396, .t400, .t404, .t409, .t410, .t412, .t418, .t422, .t425, .t428, .t433, .t456, .t477, .t478, .t480, .t486, .t498, .t504, .t506, .t509, .t511, .t517, .t518, .t519, .t520, .t532, .t533, .t538, .t539, .t544, .t545, .t552, .t554, .t570, .t577, .t592, .t598, .t599, .t601, .t604, .t605, .t609, .t615, .t616, .t650, .t659, .t670, .t675, .t686, .t688, .t694, .t698, .t700, .t726, .t728, .t730, .t734, .t738, .t740, .t744, .t754, .t760, .t762, .t764, .t774, .t776, .t778, .t780, .t786, .t798, .t799, .t801, .t813, .t814, .t822, .t826, .t827, .t829, .t842, .t843, .t849, .t850, .t851, .t856, .t858, .t859, .t860, .t881, .t902, .t912, .t923, .t937, .t959, .t983, .t979').trigger('displayChanged')});t397_startUpdateLazyLoad($(this));if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}});t397_alltabs_updateContent(recid);t397_updateContentBySelect(recid);var bgcolor=el.css("background-color");var bgcolor_target=el.find(".t397__select, .t397__firefoxfix");bgcolor_target.css("background-color",bgcolor)}
$('.r').on('click','[href*="#!/tab/'+recid+'"]',function(e){var hash=e.currentTarget.hash;t397_scrollToTabs(recid,hash)})}
function t397_alltabs_updateContent(recid){var mainRecid=recid;var el=$('#rec'+recid);var activeTab=el.find(".t397__tab_active");if(activeTab.length===1){var active=activeTab.attr('data-tab-rec-ids').split(',');var noactive=[];el.find(".t397__tab:not(.t397__tab_active)").each(function(i,tab){noactive=noactive.concat($(tab).attr('data-tab-rec-ids').split(','))});var unique=noactive.filter(function(value,index,self){return self.indexOf(value)===index});var off=unique.filter(function(value){return $.inArray(value,active)===-1});if(el.find(".t397__tab_active").is(":visible")||el.find(".t397__select").is(":visible")){active.forEach(function(recid){if(recid!==''){var el=$('#rec'+recid);var recordType=el.attr('data-record-type');el.removeClass('t397__off');el.css('opacity','');if(recordType==='395'&&t395_alltabs_updateContent!==undefined&&t395_updateSelect!==undefined&&mainRecid!==recid){t395_alltabs_updateContent(recid);t395_updateSelect(recid);el.find('.t395__tab:nth-child(1)').trigger('click')}
if(recordType==='397'&&mainRecid!==recid){t397_alltabs_updateContent(recid);t397_updateSelect(recid);el.find('.t397__tab:nth-child(1)').trigger('click')}}})}else{active.forEach(function(recid){var el=$('#rec'+recid);el.attr('data-animationappear','off');el.addClass('t397__off')})}
off.forEach(function(recid){if(recid!==''){var el=$('#rec'+recid);var recordType=el.attr('data-record-type');el.attr('data-connect-with-tab','yes');el.attr('data-animationappear','off');el.addClass('t397__off');if(recordType==='395'&&t395_alltabs_updateContent!==undefined&&t395_updateSelect!==undefined&&mainRecid!==recid){t395_alltabs_updateContent(recid);t395_updateSelect(recid);el.find('.t395__tab:nth-child(1)').trigger('click')}
if(recordType==='397'&&mainRecid!==recid){t397_alltabs_updateContent(recid);t397_updateSelect(recid);el.find('.t397__tab:nth-child(1)').trigger('click')}}})}}
function t397_updateContentBySelect(recid){var el=$('#rec'+recid);el.find(".t397__select").change(function(){var select_val=el.find(".t397__select").val();var tab_index=el.find(".t397__tab[data-tab-rec-ids='"+select_val+"']");tab_index.trigger('click')})}
function t397_updateSelect(recid){var el=$('#rec'+recid);var current_tab=el.find(".t397__tab_active").attr('data-tab-rec-ids');var el_select=el.find(".t397__select");el_select.val(current_tab)}
function t397_startUpdateLazyLoad($this){var rec_ids=$this.attr('data-tab-rec-ids').split(',');rec_ids.forEach(function(rec_id,i,arr){var rec_el=$('#rec'+rec_id);var video=rec_el.find('.t-video-lazyload');if(video.length>0){t397_updateVideoLazyLoad(video)}})}
function t397_updateVideoLazyLoad(video){setTimeout(function(){video.each(function(){var div=$(this);if(!div.hasClass('t-video__isload')){var height=div.attr('data-videolazy-height')?$(this).attr('data-videolazy-height'):'100%';if(height.indexOf('vh')!=-1){height='100%'}
var videoId=div.attr('data-videolazy-id').trim();var blockId=div.attr('data-blocklazy-id')||'';if(typeof div.attr('data-videolazy-two-id')!='undefined'){var videoTwoId='_'+div.attr('data-videolazy-two-id')+'_'}else{var videoTwoId=''}
if(div.attr('data-videolazy-type')=='youtube'){div.find('iframe').remove();div.prepend('<iframe id="youtubeiframe'+videoTwoId+blockId+'" width="100%" height="'+height+'" src="//www.youtube.com/embed/'+videoId+'?rel=0&fmt=18&html5=1&showinfo=0" frameborder="0" allowfullscreen></iframe>')}}
div.addClass('t-video__isload')})},2)}
function t397_scrollToTabs(recid,hash){var el=$('#rec'+recid);var curUrl='';if(hash){curUrl=hash}else{curUrl=window.location.href}
var tabIndexNumber=curUrl.indexOf('#!/tab/');var tabIndexNumberStart=curUrl.indexOf('tab/');el.find('.t397__wrapper_mobile .t397__select option:eq(0)').prop('selected',!1);if(tabIndexNumber!==-1){var tabRec=curUrl.substring(tabIndexNumberStart+4,tabIndexNumberStart+4+recid.length);if(tabRec==recid){var tabBlock=$('#rec'+tabRec).find('.t397');var tabNumber=parseInt(curUrl.slice(tabIndexNumberStart+4+recid.length+1),10);el.find('.t397__tab').removeClass('t397__tab_active');el.find('.t397__tab:eq('+(tabNumber-1)+')').addClass('t397__tab_active').trigger('click');el.find('.t397__wrapper_mobile .t397__select option:eq('+(tabNumber-1)+')').prop('selected',!0);var targetOffset=tabBlock.offset().top;var target=targetOffset;if($(window).width()>960){target=targetOffset-200}else{target=targetOffset-100}
$('html, body').animate({scrollTop:target},300)}}}
function t397_removeUrl(){var curUrl=window.location.href;var indexToRemove=curUrl.indexOf('#!/tab/');if(/iPhone|iPad|iPod/i.test(navigator.userAgent)&&indexToRemove<0){indexToRemove=curUrl.indexOf('%23!/tab/')}
curUrl=curUrl.substring(0,indexToRemove);if(indexToRemove!=-1){if(typeof history.replaceState!='undefined'){window.history.replaceState('','',curUrl)}}}
function t466_highlight(){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t466__item a[href='"+url+"']").addClass("t-active");$(".t466__item a[href='"+url+"/']").addClass("t-active");$(".t466__item a[href='"+pathname+"']").addClass("t-active");$(".t466__item a[href='/"+pathname+"']").addClass("t-active");$(".t466__item a[href='"+pathname+"/']").addClass("t-active");$(".t466__item a[href='/"+pathname+"/']").addClass("t-active")}
function t466_checkAnchorLinks(recid){if($(window).width()>=960){var t466_navLinks=$("#rec"+recid+" .t466__menu a:not(.tooltipstered)[href*='#']");if(t466_navLinks.length>0){t466_catchScroll(t466_navLinks)}}}
function t466_catchScroll(t466_navLinks){var t466_clickedSectionId=null,t466_sections=new Array(),t466_sectionIdTonavigationLink={},t466_interval=100,t466_lastCall,t466_timeoutId,t466_offsetTop=$(".t466").attr("data-offset-top");if(typeof t466_offsetTop=="undefined"){t466_offsetTop=0}
t466_navLinks=$(t466_navLinks.get().reverse());t466_navLinks.each(function(){var t466_cursection=t466_getSectionByHref($(this));if(typeof t466_cursection.attr("id")!="undefined"){t466_sections.push(t466_cursection)}
t466_sectionIdTonavigationLink[t466_cursection.attr("id")]=$(this)});t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop);t466_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t466_navLinks.removeClass('t-active');t466_sectionIdTonavigationLink[t466_getSectionByHref($(this)).attr("id")].addClass('t-active');t466_clickedSectionId=t466_getSectionByHref($(this)).attr("id")}});$(window).scroll(function(){var t466_now=new Date().getTime();if(t466_lastCall&&t466_now<(t466_lastCall+t466_interval)){clearTimeout(t466_timeoutId);t466_timeoutId=setTimeout(function(){t466_lastCall=t466_now;t466_clickedSectionId=t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop)},t466_interval-(t466_now-t466_lastCall))}else{t466_lastCall=t466_now;t466_clickedSectionId=t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,t466_offsetTop)}})}
function t466_getSectionByHref(curlink){if(curlink.is('[href*="#rec"]')){return $(".r[id='"+curlink.attr("href").substring(1)+"']")}
else{return $(".r[data-record-type='215']").has("a[name='"+curlink.attr("href").substring(1)+"']")}}
function t466_highlightNavLinks(t466_navLinks,t466_sections,t466_sectionIdTonavigationLink,t466_clickedSectionId,offsetTop){var t466_scrollPosition=$(window).scrollTop(),t466_valueToReturn=t466_clickedSectionId;$(t466_sections).each(function(e){var t466_curSection=$(this),t466_sectionTop=t466_curSection.offset().top,t466_id=t466_curSection.attr('id'),t466_navLink=t466_sectionIdTonavigationLink[t466_id];if(t466_scrollPosition>=(t466_sectionTop-offsetTop)||(t466_sections[0].attr("id")==t466_id&&$(window).scrollTop()>=$(document).height()-$(window).height())){if(t466_clickedSectionId==null&&!t466_navLink.hasClass('t-active')){t466_navLinks.removeClass('t-active');t466_navLink.addClass('t-active');t466_valueToReturn=null}else{if(t466_clickedSectionId!=null&&t466_id==t466_clickedSectionId){t466_valueToReturn=null}}
return!1}});return t466_valueToReturn}
function t466_initMobileMenu(recid){var window_width=$(window).width();var el=$("#rec"+recid);if(980>window_width){el.find(".t466").each(function(){$(this).find(".t466__mobile").css("top",$(this).find(".t466__container__bg_main").innerHeight()+2);$(this).find(".t466__burger, a[href*=#]").click(function(){if($(this).is(".tooltipstered, .t794__tm-link, .t978__tm-link, .t966__tm-link")){return}
el.toggleClass('t466_opened');$(this).closest(".t466").find(".t466__mobile").slideToggle(300)})})}
$('.t466').bind('clickedAnchorInTooltipMenu',function(){el.removeClass('t466_opened');$(this).closest(".t466").find(".t466__mobile").slideUp(300)})}
function t466_appearMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t466").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.hasClass('t466__beforeready')){el.removeClass('t466__beforeready')}}else{el.addClass('t466__beforeready')}}})}
function t466_changeBgOpacityMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t466__container__bg").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacity=el.attr("data-bgopacity");var bgopacity_afterscroll=el.attr("data-bgopacity2");var menu_shadow=el.attr("data-menu-shadow");if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacity_afterscroll!="0"&&bgopacity_afterscroll!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}else{el.css("background-color",bgcolor);if(bgopacity!="0"&&bgopacity!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}})}
function t570_init(recid){if($(window).width()>750){t570_setMapHeight(recid);$(window).load(function(){t570_setMapHeight(recid)});$(window).resize(function(){t570_setMapHeight(recid)})}}
function t570_setMapHeight(recid){var t570__el=$('#rec'+recid),t570__map=t570__el.find('.t-map');var t570__textwrapper=t570__el.find('.t570__col_text').height();t570__map.css('height',t570__textwrapper).trigger('sizechange')}
function t585_init(recid){var el=$('#rec'+recid);var toggler=el.find(".t585__header");var accordion=el.find('.t585__accordion');if(accordion){accordion=accordion.attr('data-accordion')}else{accordion="false"}
toggler.click(function(){if(accordion==="true"){toggler.not(this).removeClass("t585__opened").next().slideUp()}
$(this).toggleClass("t585__opened");$(this).next().slideToggle();if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}})}
function t604_init(recid){var el=$('#rec'+recid);t604_imageHeight(recid);t604_arrowWidth(recid);t604_show(recid);t604_hide(recid);$(window).bind('resize',t_throttle(function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)}));el.find('.t604').bind('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)});t604_arrowWidth(recid)})}
function t604_show(recid){var el=$("#rec"+recid),play=el.find('.t604__play');play.click(function(){if($(this).attr('data-slider-video-type')=='youtube'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t604__iframe\" width=\"100%\" height=\"100%\" src=\"https://www.youtube.com/embed/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
if($(this).attr('data-slider-video-type')=='vimeo'){var url=$(this).attr('data-slider-video-url');$(this).next().html("<iframe class=\"t604__iframe\" width=\"100%\" height=\"100%\" src=\"https://player.vimeo.com/video/"+url+"?autoplay=1\" frameborder=\"0\" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>")}
$(this).next().css('z-index','3')})}
function t604_hide(recid){var el=$("#rec"+recid),body=el.find('.t604__frame');el.on('updateSlider',function(){body.html('').css('z-index','')})}
function t604_imageHeight(recid){var el=$("#rec"+recid);var image=el.find(".t604__separator");image.each(function(){var width=$(this).attr("data-slider-image-width");var height=$(this).attr("data-slider-image-height");var ratio=height/width;var padding=ratio*100;$(this).css("padding-bottom",padding+"%")})}
function t604_arrowWidth(recid){var el=$("#rec"+recid),arrow=el.find('.t-slds__arrow_wrapper'),slideWidth=el.find('.t-slds__wrapper').width(),windowWidth=$(window).width(),arrowWidth=windowWidth-slideWidth;if(windowWidth>960){arrow.css('width',arrowWidth/2)}else{arrow.css('width','')}}
function t607_init(recid){t607_checkAnchorLinks(recid)}
function t607_checkAnchorLinks(recid){if($(window).width()>=960){var t607_navLinks=$("#rec"+recid+" .t607__list_item a:not(.tooltipstered)[href*='#']");if(t607_navLinks.length>0){t607_catchScroll(t607_navLinks)}}}
function t607_catchScroll(t607_navLinks){var t607_clickedSectionId=null,t607_sections=new Array(),t607_sectionIdTonavigationLink={},t607_interval=100,t607_lastCall,t607_timeoutId;t607_navLinks=$(t607_navLinks.get().reverse());t607_navLinks.each(function(){var t607_cursection=t607_getSectionByHref($(this));if(typeof t607_cursection.attr("id")!="undefined"){t607_sections.push(t607_cursection)}
t607_sectionIdTonavigationLink[t607_cursection.attr("id")]=$(this)});t607_highlightNavLinks(t607_navLinks,t607_sections,t607_sectionIdTonavigationLink,t607_clickedSectionId);setTimeout(function(){t607_highlightNavLinks(t607_navLinks,t607_sections,t607_sectionIdTonavigationLink,t607_clickedSectionId)},1000);$(document).keydown(function(e){var t607_direction="";switch(e.which){case 38:t607_direction="top";break;case 40:t607_direction="bottom";break;case 33:t607_direction="top";break;case 34:t607_direction="bottom";break;default:return}
if(t607_direction!=""){var t607_curActiveSectionId=t607_getSectionByHref(t607_navLinks.filter(".t-active")).attr("id"),t607_newActiveSectionIndex=$.map(t607_sections,function(obj,index){if(obj.attr("id")==t607_curActiveSectionId&&t607_direction=="top"){return index+1}
if(obj.attr("id")==t607_curActiveSectionId&&t607_direction=="bottom"){return index-1}});var t607_newActiveSection=t607_sections[t607_newActiveSectionIndex[0]];if(typeof t607_newActiveSection=="undefined"){return}
t607_navLinks.removeClass('t-active');var $root=$('html, body'),t607_offsetTop=$(".t607").attr("data-offset-top");t607_sectionIdTonavigationLink[t607_newActiveSection.attr("id")].addClass('t-active');t607_clickedSectionId=t607_newActiveSection.attr("id");if(typeof t607_offsetTop!="undefined"){$root.animate({scrollTop:t607_newActiveSection.offset().top-t607_offsetTop},500)}
else{$root.animate({scrollTop:t607_newActiveSection.offset().top},500)}}});t607_navLinks.click(function(){if(!$(this).hasClass("tooltipstered")){t607_navLinks.removeClass('t-active');var t607_clickedSection=t607_getSectionByHref($(this)),$root=$('html, body'),t607_offsetTop=$(".t607").attr("data-offset-top");if(!$(this).hasClass("t-active")){t607_clickedSectionId=t607_clickedSection.attr("id")}
t607_sectionIdTonavigationLink[t607_clickedSection.attr("id")].addClass('t-active');if(typeof t607_offsetTop!="undefined"){$root.animate({scrollTop:t607_clickedSection.offset().top-t607_offsetTop},500)}
else{$root.animate({scrollTop:t607_clickedSection.offset().top},500)}
return!1}});$(window).scroll(function(){var t607_now=new Date().getTime();if(t607_lastCall&&t607_now<(t607_lastCall+t607_interval)){clearTimeout(t607_timeoutId);t607_timeoutId=setTimeout(function(){t607_lastCall=t607_now;t607_clickedSectionId=t607_highlightNavLinks(t607_navLinks,t607_sections,t607_sectionIdTonavigationLink,t607_clickedSectionId)},t607_interval-(t607_now-t607_lastCall))}else{t607_lastCall=t607_now;t607_clickedSectionId=t607_highlightNavLinks(t607_navLinks,t607_sections,t607_sectionIdTonavigationLink,t607_clickedSectionId)}})}
function t607_getSectionByHref(curlink){var t651_curLinkValue=curlink.attr("href").replace(/\s+/g,'');if(curlink.is('[href*="#rec"]')){return $(".r[id='"+t651_curLinkValue.substring(1)+"']")}else{return $(".r[data-record-type='215']").has("a[name='"+t651_curLinkValue.substring(1)+"']")}}
function t607_highlightNavLinks(t607_navLinks,t607_sections,t607_sectionIdTonavigationLink,t607_clickedSectionId){var t607_scrollPosition=$(window).scrollTop(),t607_valueToReturn=t607_clickedSectionId;if(typeof t607_sections[t607_sections.length-2]!="undefined"&&t607_sections[t607_sections.length-2].offset().top<=$(window).height()/2&&t607_scrollPosition==0){t607_navLinks.removeClass('t-active');t607_navLink=t607_sectionIdTonavigationLink[t607_sections[t607_sections.length-1].attr("id")];t607_navLink.addClass('t-active');return null}
$(t607_sections).each(function(e){var t607_curSection=$(this),t607_sectionTop=t607_curSection.offset().top,t607_id=t607_curSection.attr('id'),t607_navLink=t607_sectionIdTonavigationLink[t607_id];if((t607_scrollPosition+$(window).height()/2)>=t607_sectionTop||(t607_sections[0].attr("id")==t607_id&&$(window).scrollTop()>=$(document).height()-$(window).height())){if(t607_clickedSectionId==null&&!t607_navLink.hasClass('t-active')){t607_navLinks.removeClass('t-active');t607_navLink.addClass('t-active');t607_valueToReturn=null}else{if(t607_clickedSectionId!=null&&t607_id==t607_clickedSectionId){t607_valueToReturn=null}}
return!1}});return t607_valueToReturn}
function t674_init(recid){var el=$("#rec"+recid);el.find('.t674__img-holder').on('load',function(){var delay=0;if($('#allrecords').attr('data-blocks-animationoff')!=='yes'){delay=600}
setTimeout(function(){$('body').addClass('t674__body_with-bg')},delay)}).each(function(){if(this.complete)$(this).load()})}
function t678_onSuccess(t678_form){var t678_inputsWrapper=t678_form.find('.t-form__inputsbox');var t678_inputsHeight=t678_inputsWrapper.height();var t678_inputsOffset=t678_inputsWrapper.offset().top;var t678_inputsBottom=t678_inputsHeight+t678_inputsOffset;var t678_targetOffset=t678_form.find('.t-form__successbox').offset().top;if($(window).width()>960){var t678_target=t678_targetOffset-200}else{var t678_target=t678_targetOffset-100}
if(t678_targetOffset>$(window).scrollTop()||($(document).height()-t678_inputsBottom)<($(window).height()-100)){t678_inputsWrapper.addClass('t678__inputsbox_hidden');setTimeout(function(){if($(window).height()>$('.t-body').height()){$('.t-tildalabel').animate({opacity:0},50)}},300)}else{$('html, body').animate({scrollTop:t678_target},400);setTimeout(function(){t678_inputsWrapper.addClass('t678__inputsbox_hidden')},400)}
var successurl=t678_form.data('success-url');if(successurl&&successurl.length>0){setTimeout(function(){window.location.href=successurl},500)}}
function t686_init(recid){setTimeout(function(){t686_setHeight(recid)},500);var t686__doResize;$(window).resize(function(){clearTimeout(t686__doResize);t686__doResize=setTimeout(function(){t686_setHeight(recid)},200)})}
function t686_setHeight(recid){var t686_el=$('#rec'+recid+' .t686'),t686_ratio=t686_el.attr('data-tile-ratio'),t686_ratioHeight=t686_el.find('.t686__col').width()*t686_ratio;t686_el.find('.t686__row').each(function(){var t686_largestHeight=0,t686_currow=$(this);$('.t686__table',this).each(function(){var t686_curCol=$(this),t686_curColHeight=t686_curCol.find(".t686__textwrapper").outerHeight();if($(this).find(".t686__cell").hasClass("t686__button-bottom")){t686_curColHeight+=t686_curCol.find(".t686__button-container").outerHeight()}
if(t686_curColHeight>t686_largestHeight){t686_largestHeight=t686_curColHeight}});if($(window).width()>=960){if(t686_largestHeight>t686_ratioHeight){$('.t686__table',this).css('height',t686_largestHeight)}
else{$('.t686__table',this).css('height',t686_ratioHeight)}
$('.t686__table',this).css('min-height','auto')}else{$('.t686__table',this).css('min-height',t686_ratioHeight);$('.t686__table',this).css('height','')}
if(t686_GetIEVersion()>0){var curRowHeight=$('.t686__table',this).css('height');$('.t686__bg',this).css('height',curRowHeight);$('.t686__overlay',this).css('height',curRowHeight)}})}
function t686_GetIEVersion(){var sAgent=window.navigator.userAgent;var Idx=sAgent.indexOf("MSIE");if(Idx>0){return parseInt(sAgent.substring(Idx+5,sAgent.indexOf(".",Idx)))}else{if(!!navigator.userAgent.match(/Trident\/7\./)){return 11}else{return 0}}}
function t734_init(recid){var rec=$('#rec'+recid);if($('body').find('.t830').length>0){if(rec.find('.t-slds__items-wrapper').hasClass('t-slds_animated-none')){t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})}else{setTimeout(function(){t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})},500)}}else{t_onFuncLoad('t_sldsInit',function(){t_sldsInit(recid)})}
rec.find('.t734').bind('displayChanged',function(){t_onFuncLoad('t_slds_updateSlider',function(){t_slds_updateSlider(recid)})})}
function t802_insta_init(recid,instauser){var projectid=$('#allrecords').attr('data-tilda-project-id');t802_insta_loadflow(recid,projectid,instauser)}
function t802_insta_loadflow(recid,projectid,instauser){if(instauser==''){var url="https://insta.tildacdn.com/fish/0.json"}else{var url="https://insta.tildacdn.com/json/project"+projectid+"_"+instauser+".json"}
$.ajax({type:"GET",url:url,dataType:"json",success:function(data){if(typeof data=='object'){t802_insta_draw(recid,data)}else{console.log('error. insta flow json not object');console.log(data)}},error:function(){console.log('error load instgram flow')},timeout:1000*90})}
function t802_insta_draw(recid,obj){if(typeof obj.photos=='undefined'){return}
$.each(obj.photos,function(index,item){t802_insta_drawItem(recid,obj.username,item)});if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){t_onFuncLoad('t_lazyload_update',function(){t_lazyload_update()})}}
function t802_insta_drawItem(recid,username,item){var emptyEl=$("#rec"+recid).find(".t802__imgwrapper_empty").first();if(emptyEl.length>0){emptyEl.removeClass("t802__imgwrapper_empty");if(window.lazy==='y'||$('#allrecords').attr('data-tilda-lazy')==='yes'){emptyEl.append('<div class="t802__bgimg t-bgimg" data-original="'+item.url+'"></div>')}else{emptyEl.append('<div class="t802__bgimg" style="background-image:url('+item.url+')"></div>')}
emptyEl.wrap('<a href="'+item.link+'" target="_blank"></a>');var hoverEl=emptyEl.find(".t802__hover-wrapper");if(hoverEl.length>0&&isMobile==!1){var text=t802_insta_cropText(recid,'@'+username+': '+item.text);hoverEl.append('<div class="t802__hover-filter"></div>');hoverEl.append('<div class="t802__text t-text t-descr_xxs">'+text+'</div>')}}}
function t802_insta_cropText(recid,text){var colsInLine=$("#rec"+recid).find("[data-cols-in-line]").attr("data-cols-in-line");if(colsInLine==6){var maxLength=90}else{var maxLength=130}
if(text.length>maxLength){text=text.substring(0,maxLength);text=text.substring(0,Math.min(maxLength,text.lastIndexOf(" ")));text+=' ...'}
return text}
function t821_init(recid){var rec=$('#rec'+recid);var el=rec.find('.t821');var isFixed=(el.css('position')=='fixed');var redactorMode=el.hasClass('t821_redactor-mode');if(!redactorMode){el.removeClass('t821__beforeready');if(isFixed&&el.attr('data-bgopacity-two')){t821_changebgopacitymenu(recid);$(window).bind('scroll',t_throttle(function(){t821_changebgopacitymenu(recid)},200))}
if(isFixed&&el.attr('data-appearoffset')){el.removeClass('t821__beforeready');t821_appearMenu(recid);$(window).bind('scroll',t_throttle(function(){t821_appearMenu(recid)},200))}}
t821_setBg(recid);$(window).bind('resize',t_throttle(function(){t821_setBg(recid)},200))}
function t821_setBg(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);if(el.attr('data-bgcolor-setbyscript')=="yes"){var bgcolor=el.attr("data-bgcolor-rgba");el.css("background-color",bgcolor)}})}else{$(".t821").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-hex");el.css("background-color",bgcolor);el.attr("data-bgcolor-setbyscript","yes")})}}
function t821_appearMenu(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}}
function t821_changebgopacitymenu(recid){var window_width=$(window).width();if(window_width>980){$(".t821").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacityone=el.attr("data-bgopacity");var bgopacitytwo=el.attr("data-bgopacity-two");var menushadow=el.attr("data-menushadow");if(menushadow=='100'){var menushadowvalue=menushadow}else{var menushadowvalue='0.'+menushadow}
if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacitytwo=='0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}else{el.css("background-color",bgcolor);if(bgopacityone=='0.0'||menushadow==' '){el.css("box-shadow","none")}else{el.css("box-shadow","0px 1px 3px rgba(0,0,0,"+menushadowvalue+")")}}})}}
function t821_createMobileMenu(recid){var window_width=$(window).width(),el=$("#rec"+recid),menu=el.find(".t821"),burger=el.find(".t821__mobile");burger.click(function(e){menu.fadeToggle(300);$(this).toggleClass("t821_opened")})
$(window).bind('resize',t_throttle(function(){window_width=$(window).width();if(window_width>980){menu.fadeIn(0)}},200))}